Reservation system, testing, etc.
vu-sa/vusa.lt pull request #215
Opened 2023-06-28 19:46 UTC by justinaskav

This pull request adds a reservation system feature and (finally) tries to use back-end and front-end testing.

More info and a better description later.

2023-07-07 00:43 UTC, justinaskav commented
@gustaz Dar nėra pabaigta, bet gali apsipažinti jau su platforma

2023-07-07 06:05 UTC, mrghosti3 commented on app/Exceptions/Handler.php
> +                'statusCode' => $response->getStatusCode(),
Galima perdėlioti metodo logiką iš kažka tokio:

```php
if (!in_array($response->getStatusCode(), [403])
    || !$response->headers->get('x-inertia') === 'true')
{
    return $response;
}

return back()->with([
    'info' => $e->getMessage() ?? 'Neturite teisių atlikti šiam veiksmui.',
    'statusCode' => $response->getStatusCode(),
]);
```

2023-07-11 23:36 UTC, justinaskav commented
@gustaz Nieko _major_ nebeplanuoju daryti atm, nebent peržiūrėjus tau ar kitiem norėtųsi dar kažko.

2023-07-24 13:51 UTC, mrghosti3 commented
Dar trumpas komentaras. Jeigu yra klasės, kurios paveldi (`extend`) kitos klasės `abstract` metodus, bet jų implementacija yra tuščia (does nothing), tai geriau tokia implementaciją dėti ant source. Dirbu prie commit su kuriuom pademonstruosiu ką turiu omenyje.

2023-07-25 00:35 UTC, justinaskav commented
@gustaz What is the expectation about tasks? Right now, on reservation resource creation, managers will get the tasks.

2023-07-28 07:22 UTC, mrghosti3 requested changes

2023-07-28 07:25 UTC, mrghosti3 commented on app/Models/Media.php
Changes already in #235

2023-07-29 21:43 UTC, gustaz approved these changes

2023-07-29 21:46 UTC, gustaz commented
Merged into main

2023-07-29 21:46 UTC, closed without merging

2023-07-29 22:39 UTC, mrghosti3 commented
Not sure this was merged

2023-07-30 09:19 UTC, justinaskav commented
I fix this today