Bunch of front-end fixes, summercamps 2023 and individual studies pages
vu-sa/vusa.lt pull request #236
Opened 2023-07-27 21:57 UTC by gustaz

- Added summercamps 2023 page and front-end changes with it
- Events list changed to 4, included responsiveness changes 
- Section about individual studies to prepare for upcoming content

2023-07-27 22:33 UTC, justinaskav reviewed
Visai nice, jau panašu, kad gettini the hang of it. 😄

2023-07-27 22:33 UTC, justinaskav commented on resources/js/Components/Public/FullWidth/SummerCamps.vue
> +        <NButton round size="large" strong type="secondary"
`type="secondary"` pasirinkimas neegzistuoja NButton komponente. Ir jeigu pažiūrėsi light mode, yra problema su šiuo mygtuku.

<img width="370" alt="image" src="https://github.com/vu-sa/vusa.lt/assets/23059846/f8c48636-dc0d-42de-ad13-2b6cd02d3354">


turėtų būti 

```suggestion
        <NButton round size="large" strong secondary
```

2023-07-27 22:33 UTC, justinaskav commented on resources/js/Components/Public/FullWidth/EventCalendarElement.vue
> +        class="basis-1/2 md:basis-1/5 md:grow"
Dabar jeigu vienas renginys, rodo taip:

<img width="1195" alt="image" src="https://github.com/vu-sa/vusa.lt/assets/23059846/3b464aa9-6a97-4f6e-b86b-1831c68399c7">

2023-07-27 22:41 UTC, gustaz commented on resources/js/Components/Public/FullWidth/SummerCamps.vue
> +        <NButton round size="large" strong type="secondary"
resolved by suggestion

2023-07-27 22:42 UTC, gustaz commented on resources/js/Components/Public/FullWidth/EventCalendarElement.vue
> +        class="basis-1/2 md:basis-1/5 md:grow"
added basis only in case there is more than one event

2023-07-27 23:07 UTC, justinaskav approved these changes

2023-07-28 08:01 UTC, mrghosti3 requested changes

2023-07-28 08:01 UTC, mrghosti3 commented on app/Http/Controllers/Public/MainController.php
> +    }
This method too many things going on in a single line. Try using more vertical space instead of horizontal:

```php
    public function summerCamps2023()
    {
        // get events with category of freshmen camps
        $events = Calendar::whereHas('category', function (Builder $query) {
            $query->where('name', '=', 'Pirmakursių stovykla');
        })
        ->with('padalinys:id,alias,fullname')
        ->with(['media'])
        ->get()
        ->sortBy('padalinys.alias');

        return Inertia::render(
            'Public/SummerCamps2023',
            [
                'events' => $events->makeHidden(['description', 'location', 'category', 'url', 'user_id', 'extra_attributes'])
                ->values()
                ->all()
            ]
        )->withViewData([
            'title' => 'Pirmakursių stovyklos',
            'description' => 'Universiteto tvarka niekada su ja nesusidūrusiam žmogui gali pasirodyti labai sudėtinga ir būtent dėl to jau prieš septyniolika metų Vilniaus universiteto Studentų atstovybė (VU SA) surengė pirmąją pirmakursių stovyklą.',
        ]);
    }
```

And also, could `description` be made into a translation or string resource instead of pasted in PHP code? I think it takes of way to much space here, but if nothing can be done about then it can be left there.

PS. same for `MainController ::summerCamps2022`

2023-07-28 10:24 UTC, justinaskav commented on app/Http/Controllers/Public/MainController.php
> +    }
IMO, if the linter doesn't fix it automatically, it can pass. If it's a problem it should be fixed by a formatter during CI actions. And about the strings, there can be a class created in e.g. `App/Constants/HTMLHeadStrings` or something else, but it may be done as a separate pull, while taking care of the whole SEO for the site.

2023-07-28 12:27 UTC, mrghosti3 commented on app/Http/Controllers/Public/MainController.php
> +    }
Ok, fair enough. We will see possible ways to change how we store large strings on other PRs. As for code formatting if we have them automated in this repo, then I'm closing my review as all good.

2023-07-28 12:27 UTC, mrghosti3 approved these changes

2023-07-29 18:42 UTC, merged